---
experiment:
  name: mitstates/base
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: SFF
  dropout: true
  norm: true
  nlayers: 1
  fc_emb: 1024,2048
  emb_dim: 512
  emb_init: ft+w2v
  use_cge: true
  gcn_type: gcn
  gr_emb: d4096,d
  graph_init: utils/mitstates-graph.t7
  image_extractor: resnet18
  use_gfn: true
  gfn_arch: gfnet-h-ti
  use_calibration: true
  calibration_weights: 0.005
  unseen_smooth: 0.1
  smp_weight: 1.0
  fuse_weight: 0
  train_only: true
training:
  max_epochs: 100
  batch_size: 128
  test_batch_size: 32
  test_set: val
  eval_val_every: 1
  lr: 5.0e-05
  wd: 5.0e-05
  fuse_lr: 1.0e-06
  fuse_wd: 1.0e-06
  lrg: 5.0e-6
  margin: 0.5
  attr_loss_w: 0.01
  obj_loss_w: 0.01
  cosine_scale: 20
  norm_family: imagenet
  save_every: 1000
  topk: 1
  workers: 2
  finetune_backbone: false
  use_precomputed_features: true
  freeze_features: false
  load_save_embeddings: true
validating:
  attr_score_weight: 0.01
  obj_score_weight: 0.01

