---
experiment:
  name: utzappos/record
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: SFF
  dropout: true
  norm: true
  nlayers: 3
  fc_emb: 1024,2048
  gr_emb: d4096,d
  emb_dim: 300
  emb_init: glove
  use_cge: false
  image_extractor: resnet18
  use_gfn : true
  gfn_arch : gfnet-h-ti
  use_calibration : true
  calibration_weights: 0.05
  unseen_smooth: 0.1
  smp_weight: 0.1
  fuse_weight: 1.0
  train_only: true

training:
  batch_size: 128
  test_batch_size: 64
  max_epochs: 100
  lr: 1.0e-05
  wd: 1.0e-05
  fuse_lr: 1.0e-05
  fuse_wd: 1.0e-05
  lrg: 5.0e-6
  eval_val_every: 1
  margin: 0.5
  cosine_scale: 50
  attr_loss_w: 1.0
  obj_loss_w: 1.0
  norm_family: imagenet
  save_every: 10000
  test_set: val
  topk: 1
  workers: 8
  finetune_backbone: false
  use_precomputed_features: true
  freeze_features: false
  load_save_embeddings: true
validating:
  attr_score_weight: 1.0
  obj_score_weight: 1.0